version: '3.3'

services:
  arquiveinfe:
    build:
      context: ../
      dockerfile: ../Dockerfile
      args:
        buildno: 1
    ports:
      - 8080:8080
    links:
      - db:pgdb
    depends_on:
      - db
      - rabbitmq
      - redis-cache

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./rabbitmq/definitions.json:/etc/rabbitmq/definitions.json:ro
      - ./rabbitmq/rabbitmq.config:/etc/rabbitmq/rabbitmq.config:ro

  redis-cache:
    image: redis:alpine
    hostname: redis
    ports:
      - 6379:6379

  db:
    image: postgres:9.5
    container_name: pgdb
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=arquiveinfe
    ports:
      - 5432:5432